Sprint 3
TonyBNK/middle.messenger.praktikum.yandex pull request #3
Opened 2022-06-04 19:39 UTC by TonyBNK

2022-06-05 17:18 UTC, podlovchenko requested changes
Привет, не получилось проверить работу системы, нет редиректа на страницу чатов, если пользователь в системе
Не забывай обновлять нетлифай)

2022-06-05 17:18 UTC, podlovchenko commented on src/api/authAPI.ts
> +            mode: 'cors',
Если используется по всему проекту, то было бы лучше поставить значения по умолчанию

2022-06-05 17:18 UTC, podlovchenko commented on src/api/chatsAPI.ts
> +                'content-type': 'application/json',
Заголовок стоит проставлять внутри yandexTransport, если есть data

2022-06-05 17:18 UTC, podlovchenko commented on src/components/pages/Profile/Profile.ts
> +            phone: /^[+]?[0-9]{10,15}$/,
Правила повторяются и на странице входа, и на странице регистрации, было бы лучше вынести в отдельный класс, функции или хотя бы константы

2022-06-05 17:18 UTC, podlovchenko commented on src/utils/main/httpTransport.ts
> +        // options.timeout,
Зачем?

2022-06-05 19:08 UTC, TonyBNK commented on src/api/authAPI.ts
> +            mode: 'cors',
Привет)
Нетлифай думал обновить когда учту все замечания.
Остальное всё пофиксил

2022-06-06 09:24 UTC, podlovchenko commented
Отлично, работу принимаю 👍

2022-06-06 09:24 UTC, podlovchenko approved these changes

2022-06-06 09:38 UTC, merged